### ISSUE TITLE
NotFoundException when registering to existing subcription

### ISSUE THREAD

**Issue by akira28** [Superbalist/php-pubsub-google-cloud#3]
I'm writing a consumer for the subscription 'user-registration', and I'm getting this error:
` [Google\Cloud\Core\Exception\NotFoundException]                          
  {                                                                        
    "error": {                                                             
      "code": 404,                                                         
      "message": "Resource not found (resource=default.user-registration).",  
      "status": "NOT_FOUND"                                                
    }                                                                      
  }     `

digging in the code, I've noticed that here: \Superbalist\PubSub\GoogleCloud\GoogleCloudPubSubAdapter::getSubscriptionForChannel

sending directly the channel, instead of prepending a clientIdentifier, results in a correct registration of the subscription (message are received etc.etc.)
`$subscription = $topic->subscription($channel);`

What am I doing wrong? What should I use for clientIdentifier?

**Comment by matthewgoslett** [comment]
Are you passing in autoCreateSubscriptions = false when constructing the adapter?

**Comment by akira28** [comment]
Yes

**Comment by matthewgoslett** [comment]
You'll need to set this to true.
If true, when you subscribe(), it will first check if the subscription exists, and if not, it will create it.
If false, it will assume that you've already created this subscription and won't perform this check.

**Comment by uzairjamil008** [comment]
gfg
